apiVersion: v2
name: quackito
description: A virtual pet duck PWA â€” feed it, play with it, watch it grow
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "16.4.4"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
