apiVersion: v1
kind: Service
metadata:
  name: {{ include "quackito.fullname" . }}-client
  labels:
    {{- include "quackito.client.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "quackito.client.selectorLabels" . | nindent 4 }}
