apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quackito.fullname" . }}-client
  labels:
    {{- include "quackito.client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      {{- include "quackito.client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quackito.client.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
